-- 006 · 관문 이전에 들어온 **워크트리 접두** 발자국을 지운다 (schema_version 5 → 6)
--
-- ★ 005 와 무엇이 다른가 — 사유가 정반대다. 005 의 근거 ⒝ 는 "지우는 것은 읽는 쪽이 이미
--   배제한 행"이었다(절대경로는 comparablePath 가 처방 축에서 뺀다). **이 행들에는 그 문장이
--   거짓이다.** 접두 경로는 절대경로가 아니라 comparablePath 를 **통과하고**(grounded=true),
--   그 다음 pathRelated 가 성분 0번(`.flightdeck` vs `plugins`)에서 갈려 100% 안 덮인 것으로
--   세어진다. 즉 이 행들은 배제된 것이 아니라 **읽혀서 거짓 증거로 인용된다.** 절대경로보다
--   나쁘다 — 그쪽은 최소한 근거에서 빠진다.
--   실측: 이 행을 인용한 처방 19건 / 6세션, 전부 `outside:` 키(최근 2026-08-07T14:48:33Z).
--
-- ★ 왜 지금 지울 수 있나: **상류가 이 회차에 막혔다.**
--   footprint 에 쓰는 살아 있는 문은 둘뿐이다 — Beat(observed)와 Pick(claimed).
--   Pick 은 접두를 원리적으로 못 만든다(item.Paths 가 이미 저장소 상대이고 pick.go 가
--   비절대 경로를 원본 그대로 둔다). 원장이 그대로다 — 접두 행 **107건 전부 origin='observed'**.
--   그 하나뿐인 문에 이 회차가 관문을 세웠다(service/session.go 의 포함 축 둘째 겹,
--   judge.CarriesWorktreePrefix). 문 하나를 막았으므로 유입이 0이 된다.
--
--   ★ 005 와 달리 "유입이 멎은 것을 관측한 뒤"가 아니라 **관문과 같은 회차**다. 나눌 수 없다 —
--   관문만 랜딩하면 107행이 남아 거짓 처방이 계속되고, 증분만 랜딩하면 하루 10~44행씩
--   다시 쌓인다(일자별 유입 18/44/35/10).
--
-- ★ 무엇을 지우나(2026-08-07 실측 107건). **이 머리말이 그 삭제의 유일한 원장이다** —
--   지운 뒤에는 어떤 질의도 이 분포를 못 낸다.
--
--     origin                observed 107 (claimed 0)
--     접두 종류             .flightdeck/worktrees/ 107 (.claude/worktrees/ 0)
--     카드의 worktree       /home/aaron/cdo-dev/kweiza-cc-plugins   57
--                           /home/aaron/cdo-dev/context-platform    50
--                           ── 전부 **주 저장소 루트**다. 그것이 이 결함의 정의다(아래).
--     영향 세션             30곳 (그중 발자국이 0이 되는 세션 7곳)
--                                                                 ────
--                                                                  107
--
--   ★ 계약은 수가 아니다. **"접두 행이 0이 된다"** 가 계약이고 위 수치는 이 시점의 원장이다.
--
-- ★ 왜 접두를 벗겨서 살리지 않나: **형제 워크트리의 같은 이름 파일은 다른 파일이다.**
--   `.flightdeck/worktrees/A/x.go` 에서 접두를 벗기면 `x.go` 가 되는데, 그것은 주 트리의
--   `x.go` 와도 워크트리 B 의 `x.go` 와도 같은 문자열이 된다. 4530e3c 가 세운 그 판단과
--   DESIGN §3 이 일부러 없앤 조상 트리 상속을 한꺼번에 되살린다. 005 머리말 32-44 가
--   이보다 온건한 '뿌리 기준 재상대화'조차 이미 기각했고, 그 자리에서 이 축을 이 항목에
--   넘겨 뒀다("좌표계를 하나로 만드는 것은 이 증분의 축이 아니다").
--
-- ★ 왜 이 행들이 생겼나(한 문장): filepath.Rel 은 **파일시스템 포함**을 재는데 링크 워크트리는
--   `<repo>/.flightdeck/worktrees/<id>` 라 저장소 루트의 물리적 자손이다. 그래서 카드의
--   worktree 가 주 저장소 루트일 때 within=true 가 나오고 rel 이 접두를 인다. git 은 그
--   트리를 자기 것으로 안 본다(`.git/info/exclude` 에 `.flightdeck/`). 두 포함 개념이
--   갈리는 틈이 이 107행이다. 카드가 그 워크트리 **자체**면 접두가 root 에 먹혀 안 생긴다 —
--   그래서 위 분포의 worktree 열이 전부 주 저장소 루트다.
--
-- ★ 005 축과 교집합이 없다. 005 는 `substr(path,1,1)='/'`(절대경로)이고 오늘 그 모집단은
--   **0건**이다. 절대/상대라 정의상 배타적이다.
--
-- ★ 왜 되돌릴 수 있나(= TestBundledMigrationsAreAdditive 갈래 (b) 근거):
--     ⒜ footprint 는 D(파생) 계층이다. 추가 전용 트리거는 judgment·event 에만 있고,
--        footprint 는 session CASCADE 로 사라지도록 스키마가 삭제를 이미 전제한다.
--        footprint 를 참조하는 표는 없다.
--     ⒝ **지우는 행은 읽는 쪽이 거짓 증거로 쓰고 있는 행이다.** 005 의 ⒝ 를 복사하면 안 된다 —
--        그 문장은 여기서 거짓이고, 그렇게 쓰면 다음 사람이 같은 판정을 다시 못 한다.
--        살릴 방법이 없다는 결론은 같지만 이유가 다르다: 저쪽은 상대화가 불가능해서,
--        이쪽은 상대화하면 서로 다른 파일이 한 문자열로 합쳐져서다.
--     ⒞ 판올림 전에 PlanMigration 이 Backup:true 로 VACUUM INTO 백업을 뜨고, 깨지면
--        RollbackHint 가 그 파일 경로와 -wal·-shm 제거 절차를 낸다.
--        **되돌리기 서브명령은 없다** — 되돌릴 유일한 길은 그 백업 파일 손 복사다.
--
-- ★ 술어가 관문보다 좁으면 안 된다. 관문(judge.CarriesWorktreePrefix → conventionRoots)은
--   성분 삼중을 경로 **어디서나** 찾는다 — 중첩 배치
--   `.flightdeck/worktrees/A/.claude/worktrees/B/x.go` 를 위해서다. 그래서 여기도 접두형과
--   중간형을 둘 다 본다. 오늘 중간형은 0건이지만, 술어를 관문과 맞추지 않으면 그 순간
--   증분과 관문의 뜻이 갈리고 그 어긋남은 어느 화면에도 안 뜬다.
--
-- ★ 멱등이다. 두 번 돌려도 결과가 같다 — 1회차 뒤 접두 행이 0건이라 2회차는 0행에 돈다.
--   행이 0인 DB(신규 설치)에서도 안전하다.

DELETE FROM footprint
 WHERE path LIKE '.flightdeck/worktrees/%'
    OR path LIKE '.claude/worktrees/%'
    OR path LIKE '%/.flightdeck/worktrees/%'
    OR path LIKE '%/.claude/worktrees/%';
