-- 010 · 죽은 역인덱스의 값을 비운다 (schema_version 9 → 10)
--
-- ★ 왜 지금 비울 수 있나: **읽는 곳이 0이고, 이 커밋으로 쓰는 곳도 0이 된다.**
--   2026-08-21 개정으로 Store.Dependents 가 파생 질의로 바뀌면서 이 표를 읽는 문이
--   하나도 안 남았다(store/item.go 의 그 함수 머리말). 남아 있던 것은 쓰기 셋뿐이고
--   — addAfter(+1) · RemoveAfter(-n) · DeleteItem(-1), 전부 bumpDependents 경유 —
--   그 셋을 **이 커밋에서 함께 걷어낸다.** 그래서 비운 뒤 다시 채워지는 경로가 없다.
--   그 부재는 시험이 지킨다: TestItemDependentsStaysRetired(dependents_retired_test.go)가
--   쓰기 경로 넷을 실제로 태우고 표가 0행인지를 본다.
--
-- ★ 무엇을 지우나(2026-08-22 실측, 운영 원장 읽기 전용, schema_version 9).
--   **이 머리말이 그 삭제의 유일한 원장이다** — 비운 뒤에는 어떤 질의도 이 분포를 못 낸다.
--
--     행 143 · SUM(n) 222 · MAX(n) 10 · 고아 행(item 에 없는 것) 0
--       context-platform    117행 · n 합 190
--       kweiza-cc-plugins    26행 · n 합  32
--     n 분포: 0→2행 · 1→98 · 2→27 · 3→8 · 4→4 · 5→1 · 6→1 · 9→1 · 10→1
--
-- ★ **표는 망가진 것이 아니라 다른 질문에 답하고 있다.** 이 구분이 이 증분의 근거다.
--   전수 대조(143행, 예외 0): `n` 은 그 항목을 dep_item 으로 가리키는 **item_after 간선 수**와
--   정확히 같다. 역방향 누락도 0이다(간선은 있는데 표에 행이 없는 dep_item 0건).
--   그런데 읽는 쪽이 묻던 것은 "**살아 있는** 종속 항목 수"(open·claimed, DISTINCT item_id)다.
--   그 둘이 143행 중 **117행에서 갈린다**(일치 26). 갈리는 이유는 카운터가 틀려서가 아니라
--   **닫힘을 안 세기 때문**이다 — n>0 인데 자기 항목이 이미 done·dropped 인 행이 129건이다.
--
--   앞 판단(01M0JCM61Q5YRJA01M4NKD6ZV8)이 쓰던 좌표계(열린 항목 중 n>0)도 그대로 재현된다:
--   11건 중 3건 불일치이고 그 셋은 이름까지 같다 — contracts-inbox-surface 3/0 ·
--   repo-hostname-leak-sweep 1/0 · docs-r208-connector-asset-owning-corpus 2/1.
--   (그 판단은 같은 좌표계를 14건으로 적었다. 하루 사이 항목이 닫혀 분모가 줄었을 뿐,
--    갈린 셋은 동일하다 — 분모를 정정하는 것이지 결론을 뒤집는 것이 아니다.)
--
-- ★ 왜 값을 남기면 안 되나: 이 레포는 원장을 sqlite3 으로 **직접 실측하는** 문화다.
--   읽는 코드가 없어도 사람이 읽는다. 143행이 얼어붙은 채 남으면 다음 사람이 그 수를
--   "종속 수"로 인용하는데, 위에서 봤듯 그것은 다른 축의 수다 — 항목
--   fd-item-dependents-table-has-no-readers 가 겨냥한 오독이 정확히 그 모양이다.
--   그리고 안 비우면 **신규 설치(0행)와 기존 DB(143행)가 갈린다.** 같은 버전의 DB 둘이
--   다른 내용을 갖는 상태를 만들 이유가 없다.
--
-- ★ 왜 되돌릴 수 있나(= TestBundledMigrationsAreAdditive 의 갈래 (b) 근거. 같은 근거를
--   store.go 마이그레이션 절과 설계 §7 에 함께 적었다 — 셋 중 하나만 고치면 그 시험이
--   없애려던 "문서와 코드가 갈린 상태"를 그대로 재생산한다):
--     ⒜ **구조는 안 건드린다.** 표도 인덱스도 그대로 남는다. 이 증분이 여는 조작은
--        DELETE FROM 하나이고, 구조가 사라지는 셋(DROP TABLE·DROP COLUMN·RENAME)은
--        neverExempt 라 애초에 예외로도 못 연다. 표 자체의 제거는 별도 항목이 진다 —
--        그 길은 `fd migrate [--to N]` / `fd migrate --rollback` 을 먼저 지어야 열린다.
--     ⒝ **지우는 값이 재구성된다.** 위 전수 대조가 그 근거다 — n 은 item_after 의
--        간선 수와 143행 전부에서 일치했고, item_after 는 이 증분이 한 행도 안 건드린다.
--        되돌리는 질의는 한 줄이다:
--
--          INSERT INTO item_dependents(project, item_id, n)
--          SELECT project, dep_item, COUNT(*) FROM item_after
--           WHERE dep_item IS NOT NULL GROUP BY project, dep_item;
--
--        (중복 간선은 0건이라 COUNT(*) 와 COUNT(DISTINCT item_id) 가 같은 값을 낸다.
--         그 사실도 같은 실측에서 확인했다.)
--
--        ★ **복원되는 것은 행 집합이 아니라 함수다 — 이 차이를 숨기지 않는다.**
--        운영 원장 사본으로 예행한 결과(2026-08-22, VACUUM INTO 68MB 사본, 마이그레이션
--        231ms) 위 질의는 143행 중 **141행**을 값까지 그대로 되살렸고, 못 되살린 둘은
--        `n = 0` 인 행이다(mvp-dedicated-machine-arrival · dataset-listing-api-and-screen).
--        간선이 0이면 GROUP BY 가 행을 만들 수 없기 때문이고, 그 둘은 **되살릴 값이 없다** —
--        읽는 쪽에게 "행 없음"과 "n = 0" 은 같은 값이었다(옛 Dependents 도 행이 없으면 0을
--        냈다). 즉 잃는 것은 "한때 간선이 있었다가 전부 끊겼다"는 흔적뿐이고, 그 흔적은
--        원장의 item.after.cut 이벤트가 이미 더 정확하게 들고 있다.
--     ⒞ 판올림 전에 PlanMigration 이 Backup:true 로 VACUUM INTO 백업을 뜨고, 깨지면
--        RollbackHint 가 그 파일 경로와 -wal·-shm 제거 절차까지 낸다.
--        **되돌리기 서브명령은 여전히 없다** — ⒝ 의 한 줄이나 그 백업 파일 손 복사다.
--
-- ★ WHERE 가 없다. 005·006 과 다른 점이고 의도다 — 저 둘은 한 표 안에서 지울 행과 살릴
--   행을 갈랐지만, 여기서는 **표 전체가 죽은 것**이라 살릴 행이라는 개념이 없다.
--   조건을 붙이면 안 지워진 행이 남고, 남은 행은 위 오독의 자리를 그대로 유지한다.
--
-- ★ 멱등이다. 두 번 돌려도 결과가 같다 — 1회차 뒤 0행이라 2회차는 0행에 돈다.
--   신규 설치(0행)에서도 안전하다.

DELETE FROM item_dependents;
