-- 011 · 죽은 표 item_dependents 를 걷는다.
--
-- ⒜ 무엇이 사라지나 — **빈 표 하나다.** 010 이 값을 비웠고(143행 → 0행), 읽는 문도 쓰는 문도
--    0이다. 읽는 쪽은 2026-08-21 에 item_after 파생 질의로 옮겼고(Store.Dependents),
--    쓰는 쪽은 2026-08-22 에 걷었다(bumpDependents 와 호출 셋). 즉 이 DROP 이 지우는 것은
--    데이터가 아니라 **구조**이고, 그 구조가 담고 있던 것은 이미 아무것도 없다.
--
-- ⒝ 왜 되돌릴 수 있나 — 값이 필요해지면 item_after 에서 재계산된다:
--      INSERT INTO item_dependents SELECT project, dep_item, COUNT(*)
--        FROM item_after WHERE dep_item IS NOT NULL GROUP BY 1,2
--    다만 **복원되는 것은 행 집합이 아니라 함수다.** 010 예행에서 143행 중 141행이 값까지
--    살아났고 못 살아난 둘은 n=0 인 행이라 되살릴 값 자체가 없었다(읽는 쪽에게 "행 없음"과
--    "n=0" 은 같은 값이다). 표 구조 자체는 이 파일과 schema.sql 이 정의를 들고 있다.
--
-- ⒞ 왜 지금 되나 — **이것이 이 증분의 핵심이다.** DROP TABLE 은 migrate_guard_test.go 의
--    neverExempt 에 올라 "사유를 아무리 잘 적어도" 못 지나가는 조작이었고, 그 관문이 지목한
--    유일한 길은 설계 §7 처방 ⒜ — 적용을 기동에서 분리하는 `fd migrate` 신설이었다.
--    **그 명령이 이 회차에 지어졌다.** store.Open 은 더 이상 어떤 마이그레이션도 적용하지
--    않고, 스키마가 안 맞으면 거절하며 `fd migrate` 를 가리킨다.
--
--    그래서 이 DROP 이 실패해도 **서버가 크래시루프에 빠지지 않는다.** 실패는 `fd migrate`
--    라는 한 명령 안에서 끝나고, 그 자리에서 `fd migrate --rollback` 이 판올림 전 백업으로
--    되돌린다. neverExempt 가 막으려던 상황("구조가 사라지는 조작이 기동 경로에서 돈다")이
--    구조적으로 성립하지 않게 된 것이다.
--
-- ⒟ 함께 걷은 것 — move.go 의 딸린 표 목록과 project.go 의 projectRefTables 에서 이 이름을
--    뺐다. 앞 회차에는 **일부러 남겼는데**(그 목록의 기준이 표의 생사가 아니라 컬럼 유무였고,
--    projectRefTables 는 살아 있는 스키마와 기계 대조되므로 빼면 시험이 빨개졌다), 이제는
--    표가 없으므로 그 대조가 반대로 뒤집힌다 — 남기면 빨개진다.
DROP TABLE item_dependents;
