-- 015 · 선행이 다른 프로젝트의 항목을 가리킬 수 있다 (schema_version 14 → 15)
--
-- 총괄 항목(루트)이 세부 항목(멤버 레포)으로 갈리는 것이 다중 레포 배치의 기본
-- 작업 형태인데, `item_after` 는 **같은 프로젝트 안**에서만 해석됐다. `fd move` 는 그
-- 사실을 스스로 적는다 — 옮기면 옛 프로젝트에 남은 참조가 "스키마로 표현 불가"해지고,
-- 막지는 않되 몇 건이 그렇게 되는지 수로만 알린다(MoveResult.CrossRefs).
-- 이 컬럼이 그 «표현 불가»를 «표현 가능»으로 바꾼다.
--
-- ★ **NULL = 같은 프로젝트다.** 009(judgment_link.target_project)와 **같은 관례**를
--   일부러 쓴다: 읽는 쪽이 COALESCE(dep_project, project) 로 해석하므로 증분 이전의
--   모든 선행 행이 지금까지와 똑같이 읽힌다. 관례를 새로 만들면 두 표가 서로 다른
--   방식으로 «자기 프로젝트»를 말하게 되고, 그 차이는 한쪽만 고치는 사고를 부른다.
--
-- ★ **백필이 없다.** UPDATE 백필은 파괴적 조작(opUpdateSet)이라 마이그레이션 가드에
--   걸리고, 걸리기 전에 근거가 없다 — NULL 이 이미 정확한 값이다.
--
-- ★ **CHECK 를 안 넓힌다.** 기존 CHECK 는 dep_item/dep_job/dep_sha 중 정확히 하나를
--   요구하고 그것은 그대로다. dep_project 는 그 셋 중 **dep_item 일 때만** 뜻이 있는데,
--   그 조건을 CHECK 로 적으려면 표를 다시 만들어야 하고(SQLite 는 CHECK 추가가
--   ALTER 로 안 된다) 그 관용구가 곧 파괴적 증분이다. 대신 쓰는 자리 하나가 그것을
--   지킨다(store.AddItem 의 선행 검증) — 그리고 그 규율은 시험이 문다.
--
-- ★ **FK 를 안 건다.** 대상 항목이 다른 프로젝트에 **아직 없을 수 있다**: 총괄 항목이
--   먼저 서고 멤버 세부 항목이 나중에 생기는 순서가 정상이다. 이 표에는 이미
--   dep_item 에 대한 FK 도 없다(같은 이유 — 선행은 아직 안 만들어진 것을 가리킨다).
--   실재 판정은 적격 판정(judge)이 조회로 한다.
--
-- ★ 인덱스를 안 만든다. 조회는 언제나 (project, item_id) 로 좁힌 뒤 그 안에서 몇 건을
--   보는 것이라(item_after_by_item 이 이미 그 인덱스다) dep_project 만으로 훑는 질의가
--   없다. 안 쓰는 인덱스는 쓰기마다 비용만 낸다.
--
-- ★ 순수 가산이다 — ALTER TABLE ADD COLUMN 뿐이다. 표를 안 더했으므로
--   TestDeclaredTablesMatchDesign 의 목록은 안 움직인다.

ALTER TABLE item_after ADD COLUMN dep_project TEXT;
